source 'https://rubygems.org'

ruby '3.1.2'
gem 'byebug'
gem 'colorize'
gem 'guard-rspec'
gem 'matrix'
gem 'require_all', '~> 3.0.0'
gem 'rspec', '3.11.0'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'simplecov'
gem 'tty-font'
